### ISSUE TITLE
PowerStream gets "stuck" after some time

### ISSUE THREAD

**Issue by Keff789** [svenerbe/ecoflow_dynamic_power_adjustment#10]
Hello,

my powerstream seems to get stuck after the script is running for 10-12h i would say. It only helps to completely unplug the powerstream, then it is all back to normal.
Has somebody else encountered this? I have not changed the pyscript and this is my automation:

```
alias: Nulleinspeisung
description: ""
trigger:
  - platform: time_pattern
    seconds: /10
condition:
  - type: is_battery_level
    condition: device
    device_id: xxxxx
    entity_id: xxxx
    domain: sensor
    above: 30
action:
  - service: pyscript.set_ef_powerstream_custom_load_power
    data:
      SerialNumber: HWxxxxxxxxxxxxxx
      TotalPower: "{{states('sensor.netzleistung') | float | round(0)}} "
      Automation: true
mode: single
```
