### ISSUE TITLE
Dynamic Power adjustment is not working

### ISSUE THREAD

**Issue by suchoi31** [svenerbe/ecoflow_dynamic_power_adjustment#39]
Hello and thank you in advance for maybe having a hint for me.

I set up everything like it is described here, at least I think so.

Automation looks like the following:

alias: PowerAdjustment
description: ""
triggers:
  - trigger: time_pattern
    seconds: /3
conditions: []
actions:
  - action: pyscript.set_ef_powerstream_custom_load_power
    metadata: {}
    data:
      SerialNumber: HW***
      TotalPower: "{{ states('senor.xyz') | round }}"
      Automation: true
mode: single

I put the key and secret to the pyscript.set_ef_powerstream_custom_load_power, 
which I got from Eco Flow developer site. 

Unfortunately, it doesn't work. The converter output is not adjusted. 

I read something regarding debugging, when I add the lines proposed to the automation, where can I read the debug information then? 

Thank you really in advance for supporting me.

**Comment by Just-Zuul** [comment]
the right structure is:

```
alias: PowerAdjustment
description: ""
triggers:
  - trigger: time_pattern
    seconds: /3
conditions: []
actions:
  - action: pyscript.set_ef_powerstream_custom_load_power
    metadata: {}
    data:
      SerialNumber: HW***
      TotalPower: {{ (states('sensor.YOUR_SENSOR_power_curr') | round(0))-20 }}
      Automation: true
mode: single

```

watch the yaml structure !!

this works here at my system.

when this not help, check the pyscript if you have a issue in the fields for the login keys


you can test it, when you set the value directly after TotalPower:  e.g TotalPower: 30   (maybe TotalPower: "30" I'm not care) - after 3 sec. it have to change on the app / Inverter other loads value


For Logging :

Insert in your configuration.yaml

```
logger:
  default: info
  logs:
    custom_components.pyscript: debug
```
    
look, if you have allready a LOGGER: in your configuration.yaml IF it is so, just add:
```
  default: info
  logs:
    custom_components.pyscript: debug
```
