### ISSUE TITLE
Feste Einspeisung Powerstream

### ISSUE THREAD

**Issue by Swcu38** [svenerbe/ecoflow_dynamic_power_adjustment#40]
Hallo, ich bin noch relativ neu in Homeassistant. Die Integration des Scripts sowie Python usw hat super geklappt. Ich habe nun versucht das yaml.Beispiel zu nehmen und mir daraus ein Script zu bauen mit dem ich die Grundlast Haus des Powerstream auf einen Festen Wert setzen kann. Leider bekomme ich es nur bedingt hin. Ich bekomme ihn zwar auf 0 gesetzt aber nicht mehr zurück auf seinen ursprünglichen Wert.

Könnte mir jemand mit Erfahrung vielleicht ein fertiges Script hier einstellen bzw meins berichtigen:)?

Powerstream 0029 Nulleinspeisung "
description: ""
triggers: []
conditions: []
actions:
  - data:
      SerialNumber: HW51XXXX
      TotalPower: "{{ states('sensor.powerstream_0029_other_loads') | round (-220) }}"
      Automation: false
    action: pyscript.set_ef_powerstream_custom_load_power
mode: single

Zur Erklärung: Hausgrundlast sind 220watt daher -220 im Skript.
+220 funktioniert leider nicht um es umzukehren.

Vielen Dank für die Hilfe im voraus!

**Comment by Just-Zuul** [comment]
Warum nimmst Du nicht ein input.number Feld (Einstellungen -> Geräte & Dienste -> Helfer -> input_number) zur Einstellung des Ausgabewertes des Inverters? 
Dann kannst Du einstellen, wieviel ausgegeben wird, indem du (entweder als Schieberegler oder als Eingabefeld konfiguriert) angibst, welchen Wert der other_load haben soll.

Die Entität nimmst Du dann als TotalPower:  im Format

```
data:
  SerialNumber: HW5xxxxxx
  TotalPower: >
    {{ states('input_number.inverter_festausgabe') | int - states('sensor.powerstream_0029_other_loads') | int }}
  Automation: true
action: pyscript.set_ef_powerstream_custom_load_power
```

Als Trigger für die Automatisation nimmst Du die Änderung des Wertes (state) vom input_number.HELFER. Wenn der Wert sich ändert, ändert die Automatisation den Wert am Inverter

P.S. Deine Grundformel ist schon nicht richtig - Du ziehst vom momentanen Inverteroutput 220 ab
würdest du von null zu 220 wollen wäre TotalPower: 220 - Inverter_other_loads (grob gesagt ohne Formatierung)

...................................................................................................................

english version:

Why don't you use an input_number field (Settings -> Devices & Services -> Helpers -> input_number) to set the output value of the inverter?
This way, you can determine how much is output by specifying (either as a slider or as an input field) the desired value for other_load.

Then, you use this entity as TotalPower in the following format:

```
data:
  SerialNumber: HW5xxxxxx
  TotalPower: >
    {{ states('input_number.inverter_festausgabe') | int - states('sensor.powerstream_0029_other_loads') | int }}
  Automation: true
action: pyscript.set_ef_powerstream_custom_load_power
```
As a trigger for the automation, use the change of state of  input_number.inverter_festausgabe 
When the value changes, the automation updates the value on the inverter.

P.S. Your basic formula is already incorrect – you are subtracting 220 from the current inverter output.
If you wanted to go from zero to 220, the correct formula would be:
TotalPower: 220 - Inverter_other_loads
(roughly speaking, without formatting).

**Comment by Swcu38** [comment]
Hi erstmal danke für die schnelle Hilfe. Hab das jetzt mal so erstellt aber iwas klappt da leider noch nicht. Er sagt mir immer das in der Zeile TotalPower irgendwo ein colon fehlt....

**Comment by Just-Zuul** [comment]
Passe Deine Daten an und versuche diese Automatisierung

- Alias der Automatisation wie Du sie bennen willst
- Der Name des input_number Reglers (2 mal) wie Du ihn bei Dir angelegt hast
- die Seriennummer des PS

Am einfachsten machst Du eine neue Automatisation, wechselst in den YAML Modus und kopierst den Code sauber rein. Achte auf die Einrückungen.


```
alias: Manuelle Steuerung
description: "Steuert die Ausgabe des Powerstreams anhand der Eingabe eines Input_Number - Helfers"
triggers:
  - trigger: state
    entity_id:
      - input_number.inverter_festausgabe       #hier auch den Namen des Schiebereglers ändern
conditions: []
actions:
  - action: pyscript.set_ef_powerstream_custom_load_power
    data:
      SerialNumber: HW5xxxxxx
      TotalPower: >
        {{ (states('input_number.inverter_festausgabe') | int) - (states('sensor.powerstream_0029_other_loads') | int) }}
      Automation: true
    enabled: true
mode: single
```


Adjust your data and try this automation:
- Alias of the automation as you want to name it
- The name of the input_number controller (twice), as you have set it up
- The serial number of the PS

The easiest way is to create a new automation, switch to YAML mode, and copy the code in cleanly. Pay attention to the indentation.
